export const JSON_UPDATE = 'JSON_UPDATE';

export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ALTER = 'USER_ALTER';
export const USER_DELETE = 'USER_DELETE';
export const TIMER_ADD = 'TIMER_ADD';

export const LOG_CREATE = 'LOG_CREATE';
export const LOG_DELETE = 'LOG_DELETE';
export const LOG_ACTIVATE = 'LOG_ACTIVATE';
export const LOG_DEACTIVATE = 'LOG_DEACTIVATE';
export const LOG_STATUS_TRUE = 'LOG_STATUS_TRUE';

export const LOG_INFO_UPDATE = 'LOG_INFO_UPDATE';
export const LOG_INTRO_UPDATE = 'LOG_INTRO_UPDATE';
export const LOG_NOTE_UPDATE = 'LOG_NOTE_UPDATE';
export const LOG_ITEMS_ADD = 'LOG_ITEMS_ADD';
export const LOG_ITEMS_UPDATE = 'LOG_ITEMS_UPDATE';
export const LOG_OTHERS_ADD = 'LOG_OTHERS_ADD';
export const LOG_OTHERS_UPDATE = 'LOG_OTHERS_UPDATE';
export const LOG_PLANS_UPDATE = 'LOG_PLANS_UPDATE';
export const LOG_CALL_UPDATE = 'LOG_CALL_UPDATE';
export const LOG_HISTORY_UPDATE = 'LOG_HISTORY_UPDATE';

export const LOG_INTRO_PROGRESS = 'LOG_INTRO_PROGRESS';
export const LOG_PROTO_PROGRESS = 'LOG_PROTO_PROGRESS';
export const LOG_ITEMS_PROGRESS = 'LOG_ITEMS_PROGRESS';
export const LOG_OTHERS_PROGRESS = 'LOG_OTHERS_PROGRESS';
export const LOG_PLANS_PROGRESS = 'LOG_PLANS_PROGRESS';
export const LOG_SUM_PROGRESS = 'LOG_SUM_PROGRESS';



