export const JSON_UPDATE = 'JSON_UPDATE';

export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ALTER = 'USER_ALTER';
export const USER_DELETE = 'USER_DELETE';

export const CHART_CREATE = 'CHART_CREATE';
export const CHART_DELETE = 'CHART_DELETE';
export const CHART_ACTIVATE = 'CHART_ACTIVATE';
export const CHART_DEACTIVATE = 'CHART_DEACTIVATE';
export const CHART_STATUS_TRUE = 'CHART_STATUS_TRUE';

export const CHART_INFO_UPDATE = 'CHART_INFO_UPDATE';
export const CHART_INTRO_UPDATE = 'CHART_INTRO_UPDATE';
export const CHART_ITEMS_UPDATE = 'CHART_ITEMS_UPDATE';
export const CHART_OTHERS_ADD = 'CHART_OTHERS_ADD';
export const CHART_OTHERS_UPDATE = 'CHART_OTHERS_UPDATE';
export const CHART_PLANS_UPDATE = 'CHART_PLANS_UPDATE';

export const CHART_INTRO_PROGRESS = 'CHART_INTRO_PROGRESS';
export const CHART_PROTO_PROGRESS = 'CHART_PROTO_PROGRESS';
export const CHART_ITEMS_PROGRESS = 'CHART_ITEMS_PROGRESS';
export const CHART_OTHERS_PROGRESS = 'CHART_OTHERS_PROGRESS';
export const CHART_PLANS_PROGRESS = 'CHART_PLANS_PROGRESS';



